"""Train an original FastWAM baseline with a prepared indexed RoboCOIN config.

Launch on eight GPUs through the baseline's Accelerate ZeRO-1 configuration.
Both the original FastWAM src/ directory and the RIFT checkout must be on
PYTHONPATH; model asset environment variables follow the original baseline.
"""
from __future__ import annotations

import argparse
import os
from pathlib import Path
import sys


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, required=True)
    args = parser.parse_args()
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    import torch
    from hydra.utils import instantiate
    from omegaconf import OmegaConf
    from fastwam.runtime import _mixed_precision_to_model_dtype, _resolve_train_device
    from fastwam.utils import misc as fastwam_misc
    from fastwam.utils.logging_config import setup_logging as setup_fastwam_logging
    from rift.baselines.fastwam import IndexedWan22Trainer
    from rift.runtime import build_train_dataset
    from rift.utils import misc
    from rift.utils.logging_config import setup_logging
    from rift.utils.pytorch_utils import set_global_seed

    cfg = OmegaConf.load(args.config.expanduser().resolve())
    OmegaConf.resolve(cfg)
    targets = {"rift.baselines.fastwam.create_fastwam", "rift.baselines.fastwam.create_fastwam_joint"}
    if cfg.model._target_ not in targets:
        raise ValueError("Use a config generated by prepare_fastwam_indexed_config.py.")
    if not (cfg.get("vae_cache_dir") and cfg.data.train.get("vae_cache_index_dir")):
        raise ValueError("Indexed baseline training requires the VAE cache and index.")
    if int(os.environ.get("WORLD_SIZE", "1")) != 8:
        raise ValueError("This config uses eight GPUs; launch with the baseline Accelerate ZeRO-1 config.")
    if not torch.cuda.is_available():
        raise RuntimeError("CUDA is unavailable in this execution environment.")
    rank = int(os.environ.get("RANK", "0"))
    output = Path(str(cfg.output_dir)).expanduser().resolve()
    misc.register_work_dir(str(output))
    fastwam_misc.register_work_dir(str(output))
    setup_logging(is_main_process=rank == 0)
    setup_fastwam_logging(is_main_process=rank == 0)
    if rank == 0:
        OmegaConf.save(cfg, output / "config.yaml")
    device = _resolve_train_device()
    torch.cuda.set_device(device)
    set_global_seed(int(cfg.seed))
    model = instantiate(cfg.model, model_dtype=_mixed_precision_to_model_dtype(cfg.mixed_precision), device=device)
    dataset = build_train_dataset(cfg.data)
    trainer = IndexedWan22Trainer(model=model, train_dataset=dataset, cfg=cfg)
    plugin = trainer.accelerator.state.deepspeed_plugin
    if plugin is None or int(plugin.deepspeed_config["zero_optimization"]["stage"]) != 1:
        raise ValueError("Indexed baseline training requires the audited original ZeRO-1 configuration.")
    trainer.train()


if __name__ == "__main__":
    main()
